# photo layout template
# text variables
# {DATE:%b %d, %Y}, {EVENT_NAME}, {SESSION_ID}, {APP_VERSION}


[canvas]
width = 2400
height = 3600
color = "#ffffff"

[background]
image = "assets/photo_background.png"
fit = "cover"

[[layers]]
type = "image_slot"
name = "shot1"
x = 90
y = 160
w = 1080
h = 1620
radius = 25

[[layers]]
type = "image_slot"
name = "shot2"
x = 1210
y = 160
w = 1080
h = 1620
radius = 25

[[layers]]
type = "image_slot"
name = "shot3"
x = 90
y = 1820
w = 1080
h = 1620
radius = 25

[[layers]]
type = "text"
text = '''

''' # can use vars here
x = "75%"
y = 2000
anchor = "top_center"
font = { path = "app/styles/default/assets/DejaVuSans-Bold.ttf", size = 150 }
fill = "#111111"
align = "center"

#insert a logo ... commenting this out for now 
#[[layers]]
#type = "image_overlay"
#image = ""
#x = 1140
#y = 1760
#w = 120
#h = 120
#anchor = "bottom_right"
#opacity = 0.9
