flowchart TD
CORE((**CORE
MODULES**))
a(
    **Idle / Attract Mode**
    slideshow
    START Button
    *led attract lights*
)

b(
    **Take Photo**
    show preview
    countdown
    take picture
    repeat count/take N times
    *led focus/flash lights*
)

c(
    **Preview Screen**
    *Show Preview* 
    Print?
    Yes/No
    Email?
    Yes/No
)

TBD((**PLANNED
MODULES**))

gallery(
    **Gallery**
    view event photos
    reprint photos
)

settings(
    **Settings**
    *pin protected*
    create/select event
    theme selection
    printer settings
)

config(
    **System Config**
    GPIO input / output
    printer setup
    remote access
)

f(
    **Future Ideas**
    QR downloads
    social media sharing
    online gallery uploads
)

TBD -.- gallery & f

CORE -.-> a --> b --> c --> a
CORE -.-> settings -.- config